### ISSUE TITLE
Make all edit pages functional

### ISSUE THREAD

**Issue by Zach116** [shahsn/cs340FinalProject#14]

**Comment by thuyvyng** [comment]
Isn't this just the add?  I thought we were doing add/delete instead of edit

**Comment by Zach116** [comment]
Ya that's what I mean, make add and delete functional. Which they all almost are perfect except for the order log

**Comment by thuyvyng** [comment]
whats wrong with them?

**Comment by thuyvyng** [comment]
I only have problems deleting from order log if it's an old order than I didnt make, is the issue you have?
